/*
** EPITECH PROJECT, 2020
** PSU_strace_2019
** File description:
** list
*/

#include "../include/strace.h"

const t_prototype g_syscalls[] =
{
    {"read", 3, {INT, STRING, SIZE_T}, SSIZE_T},
    {"write", 3, {INT,  STRING, SIZE_T}, SSIZE_T},
    {"open", 2, { STRING, INT}, INT},
    {"close", 1, {INT}, INT},
    {"stat", 2, { STRING, ADDR}, INT},
    {"fstat", 2, {INT, ADDR}, INT},
    {"lstat", 2, { STRING, ADDR}, INT},
    {"poll", 3, {ADDR, ADDR, INT}, INT},
    {"lseek", 3, {INT, ADDR, INT}, ADDR},
    {"mmap", 6, {ADDR, SIZE_T, INT, INT, INT, ADDR}, ADDR},
    {"mprotect", 3, {ADDR, SIZE_T, INT}, INT},
    {"munmap", 2, {ADDR, SIZE_T}, INT},
    {"brk", 1, {INT}, ADDR},
    {"sigaction", 3,
     {INT, ADDR, ADDR}, INT},
    {"sigprocmask", 3, {INT,ADDR,ADDR}, INT},
    {"sigreturn", 1, {UNSIGNED_LONG}, INT},
    {"ioctl", 2, {INT, INT}, INT},
    {"pread64", 4, {INT, ADDR, SIZE_T, ADDR}, SSIZE_T},
    {"pwrite64", 4, {INT, ADDR, SIZE_T, ADDR}, SSIZE_T},
    {"readv", 3, {INT, ADDR, INT}, SSIZE_T},
    {"writev", 3, {INT, ADDR, INT}, SSIZE_T},
    {"access", 2, { STRING, INT}, INT},
    {"pipe", 1, {INT_ARRAY}, INT},
    {"select", 5, {INT, ADDR, ADDR, ADDR, ADDR}, INT},
    {"sched_yield", 0, {VOID}, INT},
    {"mremap", 4, {ADDR, SIZE_T, SIZE_T, INT}, ADDR},
    {"msync", 3, {ADDR, SIZE_T, INT}, INT},
    {"mincore", 3, {ADDR, SIZE_T, UNSIGNED_CHAR_ARRAY}, INT},
    {"madvise", 3, {ADDR, SIZE_T, INT}, INT},
    {"shmget", 3, {ADDR, SIZE_T, INT}, INT},
    {"shmat", 3, {INT, ADDR, INT}, ADDR},
    {"shmctl", 3, {INT, INT, ADDR}, INT},
    {"dup", 1, {INT}, INT},
    {"dup2", 2, {INT, INT}, INT},
    {"pause", 0, {VOID}, INT},
    {"nanosleep", 2, {ADDR, ADDR}, INT},
    {"getitimer", 2, {INT, ADDR}, INT},
    {"alarm", 1, {UNSIGNED_INT}, UNSIGNED_INT},
    {"setitimer", 3,
     {INT, ADDR, ADDR}, INT},
    {"getpid", 0, {VOID, VOID}, ADDR},
    {"sendfile", 4, {INT, INT, ADDR, SIZE_T}, SSIZE_T},
    {"socket", 3, {INT, INT, INT}, INT},
    {"connect", 3, {INT, ADDR, ADDR}, INT},
    {"accept", 3, {INT, ADDR, ADDR}, INT},
    {"sendto", 6,
     {INT, ADDR, SIZE_T, INT,
        ADDR, ADDR}, SSIZE_T},
    {"recvfrom", 6,
     {INT, ADDR, SIZE_T, INT, ADDR, ADDR},
     SSIZE_T},
    {"sendmsg", 3, {INT, ADDR, INT}, SSIZE_T},
    {"recvmsg", 3, {INT, ADDR, INT}, SSIZE_T},
    {"shutdown", 2, {INT, INT}, INT},
    {"bind", 3, {INT, ADDR, ADDR}, INT},
    {"listen", 2, {INT, INT}, INT},
    {"getsockname", 3, {INT, ADDR, ADDR}, INT},
    {"getpeername", 3, {INT, ADDR, ADDR}, INT},
    /*
    ** display issue
    */
    {"socketpair", 4, {INT, INT, INT, INT_ARRAY}, INT},
    {"setsockopt", 5, {INT, INT, INT, ADDR, ADDR},
     INT},
    {"getsockopt", 5, {INT, INT, INT, ADDR, ADDR}, INT},
    /*
    ** definition issue
    */
    {"clone", 2, {INT_ARRAY, ADDR}, INT},
    {"fork", 0, {VOID}, ADDR},
    {"vfork", 0, {VOID}, ADDR},
    {"execve", 3, {STRING, STRING_ARRAY, STRING_ARRAY}, INT},
    {"exit", 1, {INT}, VOID},
    {"wait4", 4, {ADDR, INT_ARRAY, INT, ADDR}, ADDR},
    {"kill", 2, {ADDR, INT}, INT},
    {"uname", 1, {ADDR}, INT},
    {"semget", 3, {ADDR, INT, INT}, INT},
    {"semop", 3, {INT, ADDR, UNSIGNED_INT}, INT},
    {"semctl", 3, {INT, INT, INT}, INT},
    {"shmdt", 1, {ADDR}, INT},
    {"msgget", 2, {ADDR, INT}, INT},
    {"msgsnd", 4, {INT, ADDR, SIZE_T, INT}, INT},
    {"msgrcv", 5, {INT, ADDR, SIZE_T, LONG, INT}, SSIZE_T},
    {"msgctl", 3, {INT, INT, ADDR}, INT},
    {"fcntl", 2, {INT, INT}, INT},
    {"flock", 2, {INT, INT}, INT},
    {"fsync", 1, {INT}, INT},
    {"fdatasync", 1, {INT}, INT},
    {"truncate", 2, { STRING, ADDR}, INT},
    {"ftruncate", 2, {INT, ADDR}, INT},
    {"getdents", 3,
     {UNSIGNED_INT, ADDR, UNSIGNED_INT}, INT},
    {"getcwd", 2, { STRING, UNSIGNED_LONG}, LONG},
    {"chdir", 1, { STRING}, INT},
    {"fchdir", 1, {INT}, INT},
    {"rename", 2, { STRING,  STRING}, INT},
    {"mkdir", 2, { STRING, ADDR}, INT},
    {"rmdir", 1, { STRING}, INT},
    {"creat", 2, { STRING, ADDR}, INT},
    {"link", 2, { STRING,  STRING}, INT},
    {"unlink", 1, { STRING}, INT},
    {"symlink", 2, { STRING,  STRING}, INT},
    {"readlink", 3, { STRING,  STRING, SIZE_T}, SSIZE_T},
    {"chmod", 2, { STRING, ADDR}, INT},
    {"fchmod", 2, {INT, ADDR}, INT},
    {"chown", 3, { STRING, ADDR, ADDR}, INT},
    {"fchown", 3, {INT, ADDR, ADDR}, INT},
    {"lchown", 3, { STRING, ADDR, ADDR}, INT},
    {"umask", 1, {ADDR}, ADDR},
    {"gettimeofday", 2, {ADDR, ADDR}, INT},
    {"getrlimit", 2, {INT, ADDR}, INT},
    {"getrusage", 2, {INT, ADDR}, INT},
    {"sysinfo", 1, {ADDR}, INT},
    { "times", 1, {ADDR}, ADDR},
    /*
    ** first arg is actually enum __ptrace_request
    */
    { "ptrace", 4,
     {INT, ADDR, ADDR, ADDR}, LONG},
    {"getuid", 0, {VOID}, ADDR},
    {"syslog", 3, {INT,  STRING, INT}, INT},
    {"getgid", 0, {VOID}, ADDR},
    {"setuid", 1, {ADDR}, INT},
    {"setgid", 1, {ADDR}, INT},
    {"geteuid", 0, {VOID}, ADDR},
    {"getegid", 0, {VOID}, ADDR},
    {"setpgid", 2, {ADDR, ADDR}, INT},
    {"getppid", 0, {VOID}, ADDR},
    {"getpgrp", 0, {VOID}, ADDR},
    {"setsid", 0, {VOID}, ADDR},
    {"setreuid", 2, {ADDR, ADDR}, INT},
    {"setregid", 2, {ADDR, ADDR}, INT},
    /*
    ** display issue
    */
    {"getgroups", 2, {INT, ADDR}, INT},
    {"setgroups", 2, {SIZE_T, ADDR}, INT},
    {"setresuid", 3, {ADDR, ADDR, ADDR}, INT},
    {"getresuid", 3, {ADDR, ADDR, ADDR}, ADDR},
    {"setresgid", 3, {ADDR, ADDR, ADDR}, INT},
    {"getresgid", 3, {ADDR, ADDR, ADDR}, INT},
    {"getpgid", 1, {ADDR}, ADDR},
    {"setfsuid", 1, {ADDR}, INT},
    {"setfsgid", 1, {ADDR}, INT},
    {"getsid", 1, {ADDR}, ADDR},
    {"capget", 2, {ADDR, ADDR}, INT},
    {"capset", 2, {ADDR, ADDR}, INT},
    {"sigpending", 1, {ADDR}, INT},
    {"sigtimedwait", 3,
     {ADDR, ADDR, ADDR}, INT},
    {"sys_rt_sigqueueinfo", 3, {INT, INT, ADDR}, LONG},
    {"sigsuspend", 1, {ADDR}, INT},
    {"sigaltstack", 2, {ADDR, ADDR}, INT},
    {"utime", 2, { STRING, ADDR}, INT},
    {"mknod", 3, { STRING, ADDR, ADDR}, INT},
    {"uselib", 1, { STRING}, INT},
    {"personality", 1, {UNSIGNED_LONG}, INT},
    {"ustat", 2, {ADDR, ADDR}, INT},
    {"statfs", 2, { STRING, ADDR}, INT},
    {"fstatfs", 2, {INT, ADDR}, INT},
    /*
    ** Multiple definition. Do not display
    */
    {"sysfs", 3, {ADDR}, ADDR},
    {"getpriority", 2, {INT, INT}, INT},
    {"setpriority", 3, {INT, INT, INT}, INT},
    {"sched_setparam", 2, {ADDR, ADDR}, INT},
    {"sched_getparam", 2, {ADDR, ADDR}, INT},
    {"sched_setscheduler", 3,
     {ADDR, INT, ADDR}, INT},
    {"sched_getscheduler", 1, {ADDR}, INT},
    {"sched_get_priority_max", 1, {INT}, INT},
    {"sched_get_priority_min", 1, {INT}, INT},
    {"sched_rr_get_interval", 2, {ADDR, ADDR}, INT},
    {"mlock", 2, {ADDR, SIZE_T}, INT},
    {"munlock", 2, {ADDR, SIZE_T}, INT},
    {"mlockall", 1, {INT}, INT},
    {"munlockall", 0, {VOID}, INT},
    {"vhangup", 0, {VOID}, INT},
    {"modify_ldt", 3, {INT, ADDR, UNSIGNED_LONG}, INT},
    {"pivot_root", 2, { STRING,  STRING}, INT},
    {"_sysctl", 1, {ADDR}, INT},
    {"prctl", 5,
     {INT, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG},
     INT},
    {"arch_prctl", 2, {INT, UNSIGNED_LONG_ARRAY}, INT},
    {"adjtimex", 1, {ADDR}, INT},
    {"setrlimit", 2, {INT, ADDR}, INT},
    {"chroot", 1, { STRING}, INT},
    {"sync", 0, {VOID}, VOID},
    {"acct", 1, { STRING}, INT},
    {"settimeofday", 2, {ADDR, ADDR}, INT},
    {"mount", 5,
     { STRING,  STRING,  STRING,
        UNSIGNED_LONG, ADDR}, INT},
    {"umount2", 2, { STRING, INT}, INT},
    {"swapon", 2, { STRING, INT}, INT},
    {"swapoff", 1, { STRING}, INT},
    /*
    ** Multiple definition. Consider only using    int reboot(int cmd);
    */
    {"reboot", 4, {INT, INT, INT, ADDR}, INT},
    {"sethostname", 2, { STRING, SIZE_T}, INT},
    {"setdomainname", 2, { STRING, SIZE_T}, INT},
    {"iopl", 1, {INT}, INT},
    {"ioperm", 3, {UNSIGNED_LONG, UNSIGNED_LONG, INT}, INT},
    {"create_module", 2, { STRING, SIZE_T}, ADDR},
    {"init_module", 3, {ADDR, UNSIGNED_LONG,  STRING}, INT},
    {"delete_module", 2, { STRING, INT}, INT},
    {"get_kernel_syms", 1, {ADDR}, INT},
    {"query_module", 5,
     { STRING, INT, ADDR, SIZE_T, SIZE_T}, INT},
    {"quotactl", 4, {INT,  STRING, INT, ADDR}, INT},
    {"nfsservctl", 3,
     {INT, ADDR, ADDR}, INT},
    /*
    ** Not implemented in linux kernel
    */
    {"getpmsg", 1, {ADDR}, ADDR},
    {"putpmsg", 1, {ADDR}, ADDR},
    {"afs_syscall", 1, {ADDR}, ADDR},
    {"tuxcall", 1, {ADDR}, ADDR},
    {"security", 1, {ADDR}, ADDR},
    {"gettid", 0, {VOID}, ADDR},
    {"readahead", 3, {INT, ADDR, SIZE_T}, SSIZE_T},
    {"setxattr", 5,
     { STRING,  STRING, ADDR, SIZE_T, INT}, INT},
    {"lsetxattr", 5,
     { STRING,  STRING, ADDR, SIZE_T, INT}, INT},
    {"fsetxattr", 5,
     {INT,  STRING, ADDR, SIZE_T, INT}, INT},
    {"getxattr", 4,
     { STRING,  STRING, ADDR, SIZE_T}, SSIZE_T},
    {"lgetxattr", 4,
     { STRING,  STRING, ADDR, SIZE_T}, SSIZE_T},
    {"fgetxattr", 4, {INT,  STRING, ADDR, SIZE_T}, SSIZE_T},
    {"listxattr", 3, { STRING,  STRING, SIZE_T}, SSIZE_T},
    {"llistxattr", 3, { STRING,  STRING, SIZE_T}, SSIZE_T},
    {"flistxattr", 3, {INT,  STRING, SIZE_T}, SSIZE_T},
    {"removexattr", 2, { STRING,  STRING}, INT},
    {"lremovexattr", 2, { STRING,  STRING}, INT},
    {"fremovexattr", 2, {INT,  STRING}, INT},
    {"tkill", 2, {INT, INT}, INT},
    {"time", 1, {ADDR}, ADDR},
    {"futex", 6,
     {INT_ARRAY, INT, INT, ADDR, INT_ARRAY, INT}, INT},
    {"sched_setaffinity", 3, {ADDR, SIZE_T, ADDR}, INT},
    {"sched_getaffinity", 3, {ADDR, SIZE_T, ADDR}, INT},
    {"set_thread_area", 1, {ADDR}, INT},
    {"io_setup", 2, {UNSIGNED_INT, ADDR}, INT},
    {"io_destroy", 1, {ADDR}, INT},
    {"io_getevents", 5,
     {ADDR, LONG, LONG, ADDR, ADDR},
     INT},
    {"io_submit", 3, {ADDR, LONG, ADDR}, INT},
    {"io_cancel", 3,
     {ADDR, ADDR,ADDR}, INT},
    {"get_thread_area", 1, {ADDR}, INT},
    {"lookup_dcookie", 3, {ADDR,  STRING, SIZE_T}, INT},
    {"epoll_create", 1, {INT}, INT},
    {"epoll_ctl_old", 0, {VOID}, ADDR},
    {"epoll_wait_old", 0, {VOID}, ADDR},
    {"remap_file_pages", 5,
     {ADDR, SIZE_T, INT, SSIZE_T, INT}, INT},
    {"getdents64", 3,
     {UNSIGNED_INT, ADDR, UNSIGNED_INT}, INT},
    {"set_tid_address", 1, {INT_ARRAY}, LONG},
    /*
    ** Multiple definition
    */
    {"restart_syscall", 2, {INT, INT}, INT},
    {"semtimedop", 4,
     {INT, ADDR, UNSIGNED_INT, ADDR}, INT},
    {"fadvise64", 4, {INT, ADDR, ADDR, INT}, INT},
    {"timer_create", 3,
     {ADDR, ADDR, ADDR}, INT},
    {"timer_settime", 4,
     {ADDR, INT, ADDR, ADDR},
     INT},
    {"timer_gettime", 2, {ADDR, ADDR}, INT},
    {"timer_getoverrun", 1, {ADDR}, INT},
    {"timer_delete", 1, {ADDR}, INT},
    {"clock_settime", 2, {ADDR, ADDR}, INT},
    {"clock_gettime", 2, {ADDR, ADDR}, INT},
    {"clock_getres", 2, {ADDR, ADDR}, INT},
    {"clock_nanosleep", 4,
     {ADDR, INT, ADDR, ADDR}, INT},
    {"exit_group", 1, {INT}, INT},
    {"epoll_wait", 4, {INT, ADDR, INT, INT}, INT},
    {"epoll_ctl", 4, {INT, INT, INT, ADDR}, INT},
    {"tgkill", 3, {INT, INT, INT}, INT},
    /*
    ** display issue
    */
    {"utimes", 2, { STRING, ADDR}, INT},
    /*
    ** Not implemented
    */
    {"vserver", 2, {INT, INT}, INT},
    {"mbind", 6,
     {ADDR, UNSIGNED_LONG, INT, UNSIGNED_LONG_ARRAY,
        UNSIGNED_LONG, UNSIGNED_INT}, INT},
    {"set_mempolicy", 3, {INT, UNSIGNED_LONG_ARRAY, UNSIGNED_LONG}, INT},
    {"get_mempolicy", 5,
     {INT_ARRAY, UNSIGNED_LONG_ARRAY, UNSIGNED_LONG,
        UNSIGNED_LONG, UNSIGNED_LONG}, INT},
    /*
    ** Multiple definition
    */
    {"mq_open", 2, {INT, INT}, INT},
    {"mq_unlink", 1, { STRING}, INT},
    {"mq_timedsend", 5,
     {ADDR,  STRING, SIZE_T, UNSIGNED_INT, ADDR},
     INT},
    {"mq_timedreceive", 5,
     {ADDR,  STRING, SIZE_T, UNSIGNED_INT, ADDR}, INT},
    {"mq_notify", 2, {ADDR, ADDR}, INT},
    {"mq_getsetattr", 3,
     {ADDR, ADDR, ADDR}, INT},
    {"kexec_load", 4,
     {UNSIGNED_LONG, UNSIGNED_LONG,
        ADDR, UNSIGNED_LONG}, INT},
    {"waitid", 4, {ADDR, ADDR, ADDR, INT}, INT},
    {"add_key", 5,
     { STRING,  STRING, ADDR, SIZE_T, ADDR},
     ADDR},
    {"request_key", 4,
     { STRING,  STRING,  STRING, ADDR},
     ADDR},
    {"keyctl", 1, {INT}, INT},
    {"ioprio_set", 3, {INT, INT, INT}, INT},
    {"ioprio_get", 2, {INT, INT}, INT},
    {"inotify_init", 0, {VOID}, INT},
    {"inotify_add_watch", 3, {INT,  STRING, ADDR}, INT},
    {"inotify_rm_watch", 2, {INT, INT}, INT},
    {"migrate_pages", 4,
     {INT, UNSIGNED_LONG, UNSIGNED_LONG_ARRAY, UNSIGNED_LONG_ARRAY},
     LONG},
    /*
    ** Multiple definition
    */
    {"openat", 3, {INT,  STRING, INT}, INT},
    {"mkdirat", 3, {INT,  STRING, ADDR}, INT},
    {"mknodat", 4, {INT,  STRING, ADDR, ADDR}, INT},
    {"fchownat", 5, {INT,  STRING, ADDR, ADDR, INT}, INT},
    /*
    ** display issue
    */
    {"futimesat", 3,
     {INT,  STRING, ADDR}, INT},
    {"fstatat", 4, {INT,  STRING, ADDR, INT}, INT},
    {"unlinkat", 3, {INT,  STRING, INT}, INT},
    {"renameat", 4, {INT,  STRING, INT,  STRING}, INT},
    {"linkat", 5,
     {INT,  STRING, INT,  STRING, INT}, INT},
    {"symlinkat", 3, { STRING, INT,  STRING}, INT},
    {"readlinkat", 4, {INT,  STRING,  STRING, SIZE_T}, INT},
    {"fchmodat", 4, {INT,  STRING, ADDR, INT}, INT},
    {"faccessat", 4, {INT,  STRING, INT, INT}, INT},
    {"pselect6", 6,
     {INT, ADDR, ADDR, ADDR,
        ADDR, ADDR}, INT},
    {"ppoll", 4,
     {ADDR, ADDR,
        ADDR,ADDR}, INT},
    {"unshare", 1, {INT}, INT},
    {"set_robust_list", 2, {ADDR, SIZE_T}, LONG},
    {"get_robust_list", 5,
     {INT,  STRING, INT,  STRING, INT}, INT},
    {"splice", 6 ,
     {INT, ADDR, INT, ADDR, SIZE_T, UNSIGNED_INT}, SSIZE_T},
    {"tee", 4, {INT, INT, SIZE_T, UNSIGNED_INT}, SSIZE_T},
    {"sync_file_range", 4,
     {INT, ADDR, ADDR, UNSIGNED_INT}, INT},
    {"vmsplice", 4,
     {INT, ADDR, UNSIGNED_LONG, UNSIGNED_INT}, SSIZE_T},
    {"move_pages", 6,
     {INT, UNSIGNED_LONG, VOID_ARRAY, INT_ARRAY, INT_ARRAY, INT}, LONG},
    /*
    ** display issue
    */
    {"utimensat", 4,
     {INT,  STRING, ADDR, INT}, INT},
    {"epoll_pwait", 4,
     {INT, ADDR, INT, INT, ADDR}, INT},
    {"signalfd", 3, {INT,ADDR, INT}, INT},
    {"timerfd_create", 2, {INT, INT}, INT},
    {"eventfd", 2, {UNSIGNED_INT, INT}, INT},
    {"fallocate", 4, {INT, INT, ADDR, ADDR}, INT},
    {"timerfd_settime", 4,
     {INT, INT, ADDR, ADDR}, INT},
    {"timerfd_gettime", 2, {INT, ADDR}, INT},
    {"accept4", 4, {INT, ADDR, ADDR, INT}, INT},
    /*
    ** display issue
    */
    {"signalfd4", 3, {INT,ADDR, INT}, INT},
    /*
    ** display issue
    */
    {"eventfd2", 4,
     {INT,  STRING, ADDR, INT}, INT},
    {"epoll_create1", 1, {INT}, INT},
    {"dup2", 2, {INT, INT}, INT},
    /*
    ** display issue
    */
    {"pipe2", 2, {INT_ARRAY, INT}, INT},
    {"inotify_init1", 1, {INT}, INT},
    {"preadv", 4,
     {INT, ADDR, INT, ADDR}, SSIZE_T},
    {"pwritev", 3, {INT, ADDR, INT}, SSIZE_T},
    {"sys_rt_tgsigqueueinfo", 3, {INT, INT, ADDR}, LONG},
    /*
    ** Multiple definition
    */
    {"perf_event_open", 4,
     {INT, ADDR, ADDR, INT}, INT},
    {"recvmmsg", 5,
     {INT, ADDR, UNSIGNED_INT,
        UNSIGNED_INT, ADDR}, INT},
    /*
    ** No man
    */
    {"fanotify_init", 4,
     {INT, ADDR, ADDR, INT}, INT},
    {"fanotify_init", 4,
     {INT, ADDR, ADDR, INT}, INT},
    {"prlimit", 4,
     {ADDR, INT, ADDR, ADDR}, INT},
    /*
    ** No man
    */
    {"name_to_handle_at", 1, {INT}, INT},
    {"open_to_handle_at", 4,
     {INT, ADDR, INT, ADDR}, SSIZE_T},
    {"clock_adjtime", 3, {INT, ADDR, INT}, SSIZE_T},
    {"syncfs", 1, {INT}, INT},
    {"sendmmsg", 4,
     {INT, ADDR, UNSIGNED_INT, UNSIGNED_INT}, INT},
    {"setns", 2, {INT, INT}, INT},
    {"getcpu", 3, {ADDR, ADDR, ADDR}, INT},
    {"process_vm_readv", 6, {ADDR, ADDR, UNSIGNED_LONG,
        ADDR, UNSIGNED_LONG, UNSIGNED_LONG}, SSIZE_T},
    {"process_vm_writev", 6,
     {ADDR, ADDR, UNSIGNED_LONG,
        ADDR, UNSIGNED_LONG, UNSIGNED_LONG}, SSIZE_T},
    {"kcmp", 5, {ADDR, ADDR, INT, UNSIGNED_LONG, UNSIGNED_LONG}, INT},
    {"finit_module", 3, {INT,  STRING, INT}, INT}
};